DeclutterMeMvcUI/Areas/Admin/Controllers/ProductController.cs
using DataAccessLibrary.Data;
using DataAccessLibrary.Entities;
using DeclutterMeMvcUI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DeclutterMeMvcUI.Areas.Admin.Controllers;

[Area("Admin")]
public class ProductController : Controller
{
    private readonly DeclutterMeDbContext _db;
    private readonly IWebHostEnvironment _hostEnvironment;

    public ProductController(DeclutterMeDbContext db, IWebHostEnvironment hostEnvironment)
    {
        _db = db;
        _hostEnvironment = hostEnvironment;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> Get()
    {
        IEnumerable<Product> products = await _db.Products
            .Include(p => p.Category)
            .ToListAsync();
        return Json(new { data = products });
    }

    [HttpGet]
    public async Task<IActionResult> Upsert(int? id)
    {
        ProductUpsertModel productUpsertModel = new()
        {
            Product = new(),
            CategoryList = (await _db.Categories.ToListAsync())
                .Select(c => new SelectListItem(c.Name, c.Id.ToString()))
        };

        if (id is null || id == 0)
        {
            return View(productUpsertModel);
        }
        else
        {
            productUpsertModel.Product = await _db.Products.FirstOrDefaultAsync(p => p.Id == id);
            return View(productUpsertModel);
        }
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> UpsertAsync(ProductUpsertModel productUpdate, IFormFile file)
    {
        if (ModelState.IsValid)
        {
            string wwwRootPath = _hostEnvironment.WebRootPath;

            if (file is not null)
            {
                string fileName = $"{productUpdate.Product.Name}-{Guid.NewGuid()}";
                string uploads = Path.Combine(wwwRootPath, @"img\products");
                string extension = Path.GetExtension(file.FileName);

                Directory.CreateDirectory(uploads);

                if (productUpdate.Product.ImageUrl != null)
                {
                    string oldImagePath = Path.Combine(wwwRootPath, productUpdate.Product.ImageUrl.TrimStart('\\'));

                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                using var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create);
                file.CopyTo(fileStream);
                productUpdate.Product.ImageUrl = $@"\img\products\{fileName}{extension}";
            }

            if (productUpdate.Product.Id == 0)
            {
                await _db.Products.AddAsync(productUpdate.Product);
                TempData["success"] = "Product created successfully";
            }
            else
            {
                _db.Products.Update(productUpdate.Product);
                TempData["success"] = "Product updated successfully";
            }

            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        return View(productUpdate);
    }

    [HttpDelete]
    public async Task<IActionResult> Delete(int? id)
    {
        Product dbProduct = await _db.Products.FirstOrDefaultAsync(p => p.Id == id);

        if (dbProduct == null)
        {
            return Json(new { success = false, message = $"Product not found in database [{id}]"});
        }

        string oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, dbProduct.ImageUrl.TrimStart('\\'));

        if (System.IO.File.Exists(oldImagePath))
        {
            System.IO.File.Delete(oldImagePath);
        }

        _db.Products.Remove(dbProduct);
        await _db.SaveChangesAsync();
        return Json(new { success = true, message = $"Product deleted successfully" });
    }
}

DeclutterMeMvcUI/Controllers/CategoryController.cs
namespace DeclutterMeMvcUI.Controllers;

public class CategoryController : Controller
{
    private readonly IUnitOfWork _db;

    public CategoryController(IUnitOfWork db)
    {
        _db = db;
    }

    public async Task<IActionResult> Index()
    {
        IEnumerable<Category> categories = await _db.Category.GetAsync();
        return View(categories);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Category category)
    {
        if (category.Name == category.DisplayOrder.ToString())
        {
            ModelState.AddModelError("Name", "The DisplayOrder cannot match the Name");
        }

        if (ModelState.IsValid)
        {
            await _db.Category.AddAsync(category);
            await _db.SaveChangesAsync();
            TempData["success"] = "Category created successfully";
            return RedirectToAction("Index");
        }

        return View(category);
    }

    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }

        Category category = await _db.Category.GetAsync(c => c.Id == id);

        if (category == null)
        {
            return NotFound();
        }

        return View(category);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Category category)
    {
        if (category.Name == category.DisplayOrder.ToString())
        {
            ModelState.AddModelError("Name", "The DisplayOrder cannot match the Name");
        }

        if (ModelState.IsValid)
        {
            _db.Category.Update(category);
            await _db.SaveChangesAsync();
            TempData["success"] = "Category updated successfully";
            return RedirectToAction("Index");
        }

        return View(category);
    }

    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }

        Category category = await _db.Category.GetAsync(c => c.Id == id);

        if (category == null)
        {
            return NotFound();
        }

        return View(category);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(Category category)
    {
        Category c = await _db.Category.GetAsync(c => c.Id == category.Id);

        if (c == null)
        {
            return NotFound();
        }

        _db.Category.Remove(c);
        await _db.SaveChangesAsync();
        TempData["success"] = "Category deleted successfully";

        return RedirectToAction("Index");
    }
}

DeclutterMeMvcUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DeclutterMe</title>
    <link rel="stylesheet" href="~/css/flatly.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DeclutterMeMvcUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3 py-0">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DeclutterMe</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li class="dropdown-item">
                                    <a class="nav-link text-light" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                </li>
                                <li class="dropdown-item">
                                    <a class="nav-link text-light" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-light">
        <div class="container">
            &copy; @DateTime.Now.Year - DeclutterMe - MVC - <a asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>